services:
  minio2:
    image: minio/minio:latest
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - "13131:9000"
      # - "9982:9001" #disable l8r
    environment:
      MINIO_ROOT_USER: minioadm
      MINIO_ROOT_PASSWORD: minio123321
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    volumes:
      - minio-data2:/data
    networks:
      - minionetwork2

networks:
  minionetwork2:
    driver: bridge

volumes:
  minio-data2: