services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/minio.conf:ro
    ports:
      - "80:9000"
      - "8080:9001" # 4 testing
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - minionetwork

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "9000:9000" 
      - "9001:9001" # 4 testing
    volumes:
      - minio-data:/data
    networks:
      - minionetwork

networks:
  minionetwork:
    driver: bridge

volumes:
  minio-data: